### ISSUE TITLE
Can I fork your repository?

### ISSUE THREAD

**Issue by anuveyatsu** [ehanson8/viaf-dbpedia-reconciliation-python#1]
Hi @ehanson8 

I was wondering if it's OK to fork your repo and publish your dataset at https://datahub.io

Would you like to have credits or any sources to be specified?

Thanks!

**Comment by ehanson8** [comment]
No objection at all and just crediting me is fine. Out of curiousity, what’s your interest in these scripts?

Eric Hanson
Digital Content Metadata Specialist
The Sheridan Libraries
Johns Hopkins University
3400 North Charles Street
Baltimore, MD 21218
667-208-7431
ehanson8@jhu.edu

**Comment by anuveyatsu** [comment]
Hi @ehanson8 

I thought I can create a page where I can collect information related to VIAF so people can find everything in one place. But now it seems to be a bit complicated. I will let you know if any information from here is used.

Thanks!
